version: '3.8'
services:
  app:
    # Overrides default command so the development container keeps running until the user disconnects
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - .:/usr/src/app
      - ../../.git/:/usr/src/.git/ # Ensure git works in the devcontainer since this is a submodule
